### PR TITLE
Minor changes to readme.

### PR DESCRIPTION
**Pull request by brl0**
Added badges for downloads and for conda build status.
Added installation instructions for conda.
Once the new version is released, I am planning to update the conda-forge feedstock.

### CODE REVIEW

**Comment by kimwalisch** [comment]
I have found a minor issue (unrelated to this pull request) yesterday while reviewing your code changes. We have switched all functions to use the C API instead of the C++ API for performance reasons. However when the primesieve C API is used we need to check ```errno``` after each call into libprimesieve to know whether an error has occured. We correctly do this for ```primesieve.primes(n)``` and ```primesieve.n_primes(n)```. However for all other functions we don't do it. This means that in case an error occurs for e.g. ```primesieve.count_prime(n)``` that function will silently return an incorrect result.

The reason for this issue is that C does not support C++ exceptions. When an error occurs inside libprimesieve an exception (which contains a message of what went wrong) is thrown. However in the libprimesieve C API all exceptions are caught (inside libprimesieve) and errno is set instead.

> Along these lines, based on some quick testing, it seems the C interface is noticeably faster than the C++ interface. To test, I created another submodule based on the array submodule, and modified it to include the C++ interface rather than C. The performance matched very closely with the base module, with the array submodule based on the C interface performing much better.

Is my understand right that you only measured a speed up when using the C API for ```primesieve.primes(n)``` and ```primesieve.n_primes(n)```. If so I suggest that we switch back all other functions to the C++ API because there error handling works out of the box.

**Comment by brl0** [comment]
> If so I suggest that we switch back all other functions to the C++ API because there error handling works out of the box.

No problem, will do.  Great catch, thanks. Sorry for the oversight.

**Comment by brl0** [comment]
> Is my understand right that you only measured a speed up when using the C API for `primesieve.primes(n)` and `primesieve.n_primes(n)`.

Based on some quick testing it looks like the C version is around 3x faster than the C++ version.  I will start adding the proper error checking to the C version unless you say otherwise.

**Comment by kimwalisch** [comment]
What I wanted is to keep using the C API for primesieve.primes(n) and primesieve.n_primes(n) but use the C++ API for all other functions (e.g. the count, print, get & set functions). 

> Based on some quick testing it looks like the C version is around 3x faster than the C++ version. I will start adding the proper error checking to the C version unless you say otherwise.

I guess your benchmark results are for primesieve.primes(n) and primesieve.n_primes(n), is that correct? I also guess that for the other functions there will not be any performance improvement when using the C API...

**Comment by brl0** [comment]
> I guess your benchmark results are for primesieve.primes(n) and primesieve.n_primes(n), is that correct? I also guess that for the other functions there will not be any performance improvement when using the C API...

Running count_primes and count_twins I am getting 3x faster completion with the C version than with the C++ version.

**Comment by kimwalisch** [comment]
The code changes in this pull request have been merged by https://github.com/hickford/primesieve-python/pull/32.

**Pull request closed without merging**
