### PR TITLE
add generated cpp files & use them in setup.py if no cython installed

### PR DESCRIPTION
**Pull request by pstoll**
This PR includes the generated cpp files and fixes setup.py to work if cython is not installed. And removes the .gitignore for the generated cpp files.

fyi @kimwalisch

### CODE REVIEW

**Comment by pstoll** [comment]
@kimwalisch - It looks like Pandas, a popular data anlysis library for python, has cython as an optional buildtime dependency, much like @hickford was doing here. 

I see what you're talking about Cython versions. It looks like Pandas handles this by checking for a minimum version of Cython.

https://github.com/pydata/pandas/blob/master/setup.py#L21-L27

We can probably similarly be "inspired" by them (i.e. copy the relevant bits).

**Comment by pstoll** [comment]
Here's another setup.py that uses cython optionally https://github.com/datastax/python-driver/blob/master/setup.py

**Comment by kimwalisch** [comment]
> add generated cpp files

Is my understand correct that we can only get rid of the cython depedency if we add the generated cpp  files to the repo?

Because from my GNU Autotools (C/C++ build system) experience **one should never** add the files generated in the `./configure` step to the repo! Hence I think me must at all cost avoid adding the generated `_primesieve.cpp` and `_generate.cpp` files to the primesieve-python repo!?

Maybe the better solution would be to make cython a prerequisite for installing primesieve-python, is it really that important that primesieve-python does not depend on cython? Is it possible to automatically install cython if the user does `pip install primesieve` and he has not installed cython?

**Comment by pstoll** [comment]
@kimwalisch  I have my fair share of autogen / configure badges of honor^h^h^h^h^h horror and I share your general aversion to including auto generated code. However, if you look at the generated files, they are aware of many build environments and IFDEF'ed all over the place. 

This section of Cython says http://docs.cython.org/src/reference/compilation.html#distributing-cython-modules says:

> It is strongly recommended that you distribute the generated .c files as well as your Cython sources, so that users can install your module without needing to have Cython available.

Consider the generated code as c/c++ modules that should compile on many platforms. Instead of having been typed in by people, we just had a computer type them in. But they should work on lots of platform.

That said, this package is really just providing Python bindings to functions exported from  primesieve library. Using Cython to generate those bindings is cute/clever and makes doing it really straightforward. I tend to the side that says - requiring Cython just to install this library feels a bit much and if it is possible to support people without Cython, we should.

**Comment by kimwalisch** [comment]
@pstoll Awesome answer! I will merge your changes when I am back home.

**Comment by hickford** [comment]
As Kim says, the generated cpp don't belong in the repo. They aren't source code. So long as they are distributed _in the package_ people can install without Cython. 

See https://github.com/hickford/primesieve-python/blob/v0.1.2/setup.py#L12 for how this works

**Pull request merged**
