### PR TITLE
Generate array.array of primes

### PR DESCRIPTION
**Pull request by shlomif**
This is similar to numpy and based on it but generates https://docs.python.org/3/library/array.html . This is useful for pypy and elsewhere. The history is messy, but I can squash into one commit.

### CODE REVIEW

**Comment by shlomif** [comment]
Note that the code may not work on systems where `array("L"` items are 32-bit.

**Comment by kimwalisch** [comment]
Thanks!

I have a few questions:

So if my understanding is right, your API is identical to ```primesieve.numpy``` but the new functionality simply returns a different array type. Is there any advantage of using ```primesieve.array``` instead of ```primesieve.numpy```?

The ```primesieve.numpy``` module causes a lot of trouble e.g. for distributing primesieve Windows wheels we need to compile numpy ourselves with the correct Visual Studio version (which may change for every python release) and then link ```primesieve.numpy``` against our numpy. It is a big maintainance nightmare.

If your new functionality is very similar to ```primesieve.numpy``` and easier to maintain then I might consider removing ```primesieve.numpy``` and bumping the version number.

> Note that the code may not work on systems where array("L" items are 32-bit.

Can this be fixed? Can't we use array("Q") since Q is ```unsigned long long``` which is 64-bit on both i386 and x86_64.

**Comment by shlomif** [comment]
Hi,

> Thanks!
> 
> I have a few questions:
> 
> So if my understanding is right, your API is identical to `primesieve.numpy` but the new functionality simply returns a different array type. Is there any advantage of using `primesieve.array` instead of `primesieve.numpy`?
> 

Well, I implemented it because array.array is faster on [pypy](https://pypy.org/) so there is at least that.

> The `primesieve.numpy` module causes a lot of trouble e.g. for distributing primesieve Windows wheels we need to compile numpy ourselves with the correct Visual Studio version (which may change for every python release) and then link `primesieve.numpy` against our numpy. It is a big maintainance nightmare.

ah.

> 
> If your new functionality is very similar to `primesieve.numpy` and easier to maintain then I might consider removing `primesieve.numpy` and bumping the version number.
> 

I think one can initialise numpy arrays from array.array ones: https://stackoverflow.com/questions/5674960/efficient-python-array-to-numpy-array-conversion .

> > Note that the code may not work on systems where array("L" items are 32-bit.
> 
> Can this be fixed? Can't we use array("Q") since Q is `unsigned long long` which is 64-bit on both i386 and x86_64.

I'll try - thanks.

**Comment by shlomif** [comment]
@kimwalisch : see my latest commit - https://github.com/hickford/primesieve-python/pull/27/commits/25e9043fbfdeca98d965f2519acbcdba3b4a173d . I guess we can detect the py version and if it is 3 then use "Q" and long long, but this will require more work.

**Comment by shlomif** [comment]
> I guess we can detect the py version and if it is 3 then use "Q" and long long, but this will require more work.

This is done now.

**Comment by kimwalisch** [comment]
I like your last commit where we use array("Q") for python 3 or later and array("L") for python 2. If my understanding is correct then it will work everywhere expect on Windows 32-bit with python 2?

**Comment by kimwalisch** [comment]
Currently I offer primesieve-python binary wheels on Windows so that the user can easily install primesieve-python without first installing the Visual C++ compiler. As I have mentioned before creating these wheels is very difficult as we need to compile numpy ourselves with the correct Visual C++ compiler version (that may be different for every python version). There are installation & compilation scripts for numpy inside the appveyor directory that are hundreds of lines of code.

I am not a python expert. Do you know whether we now need a similar procedure for your ```primesieve.array``` module? Ideally I would like to simplify creating primesieve wheels on Windows and get rid of the difficult compilation procedure required by numpy.

**Comment by shlomif** [comment]
> Currently I offer primesieve-python binary wheels on Windows so that the user can easily install primesieve-python without first installing the Visual C++ compiler. As I have mentioned before creating these wheels is very difficult as we need to compile numpy ourselves with the correct Visual C++ compiler version (that may be different for every python version). There are installation & compilation scripts for numpy inside the appveyor directory that are hundreds of lines of code.
> 
> I am not a python expert. Do you know whether we now need a similar procedure for your `primesieve.array` module? Ideally I would like to simplify creating primesieve wheels on Windows and get rid of the difficult compilation procedure required by numpy.

primesieve.array should not require numpy, but still depends on cython and other stuff.

**Comment by kimwalisch** [comment]
> primesieve.array should not require numpy, but still depends on cython and other stuff.

OK thanks. I will test whether I can easily build a Windows wheel (that does not require any additional compilation and installation scripts like numpy) using your new ```primesieve.array``` module. If this works I will remove ```primesieve.numpy``` and merge your ```primesieve.array``` module.

Note that it might take me a week or so before this can be merged because I am just a casual python user so I need to take my time and thoroughly test everything.

**Comment by shlomif** [comment]
@kimwalisch : OK, thanks!

**Comment by shlomif** [comment]
@kimwalisch : hi! Any news?

**Comment by kimwalisch** [comment]
Hi,

I have not forgotten your pull request but I am currently on holiday at the beach without my notebook. Unfortunately work todo is piling up on my other open source projects too, that's why it takes more time than expected.

**Comment by shlomif** [comment]
@kimwalisch : thanks for the update. I'll wait.

**Comment by kimwalisch** [comment]
Hi Shlomi,

Just to give you some context:

The ```primesieve.numpy``` module was added because it allowed to generate an array of primes much faster then the default ```primesieve``` module. However building binary wheels with numpy is extremely painful on Windows.

For this reason if your new module is equally fast as the ```primesieve.numpy``` module I would like to get rid of the ```primesieve.numpy``` module and use your new module instead.

Also in order to make things as simple as possible it would be great if there was only 1 ```primesieve``` module. Hence ideally we would just replace the ```primes()``` and ```n_primes()``` functions from ```_primesieve.pyx``` with your new versions.

Since I am not a python expert, do you think people will complain if e.g. ```primes()``` returns a primes array instead of a primes list?

**Comment by kimwalisch** [comment]
Another big improvement would be if there were binary primesieve wheels for every single operating system and CPU architecture. Apparently there is a new tool called [Poetry](https://poetry.eustace.io/) which does this. Maybe this would also simplify building primesieve wheels with ```primesieve.numpy``` on Windows.

This blog post contains a good introduction:
https://dan.yeaw.me/posts/python-packaging-with-poetry-and-briefcase/

**Comment by shlomif** [comment]
Hi Kim,

> Hi Shlomi,
> 
> Just to give you some context:
> 
> The `primesieve.numpy` module was added because it allowed to generate an array of primes much faster then the default `primesieve` module. However building binary wheels with numpy is extremely painful on Windows.
> 

OK.

> For this reason if your new module is equally fast as the `primesieve.numpy` module I would like to get rid of the `primesieve.numpy` module and use your new module instead.
> 

Not sure I have benchmarked both.

> Also in order to make things as simple as possible it would be great if there was only 1 `primesieve` module. Hence ideally we would just replace the `primes()` and `n_primes()` functions from `_primesieve.pyx` with your new versions.
> 
> Since I am not a python expert, do you think people will complain if e.g. `primes()` returns a primes array instead of a primes list?

A list has different semantics. You can do stuff like:

```
lst[0] = {'k1':lst[0],'k2':'foo'}
lst += [700, 90, 8]
lst.append("foo")
```

which may not be possible with arrays. Given it breaks backcompat i'd recommend against it.

**Comment by shlomif** [comment]
On Wed, 20 Nov 2019 05:04:20 -0800
Kim Walisch <notifications@github.com> wrote:

> Merged #27 into master.
> 

Thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
http://is.gd/htwEXQ - Integrating GNU Guile into GNU coreutils

I’d love to change the world, but they won’t give me the source code.
    — Unknown

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Pull request merged**
