### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by shlomif**

### CODE REVIEW

**Comment by shlomif** [comment]
@kimwalisch : hi! any comments?

**Comment by kimwalisch** [comment]
> any comments?

Yes 😁 

If you think your code changes are useful then please go ahead and merge them. If you break primesieve-python I won't blame you, but I will not fix it either. Sadly I have to let go primesieve-python, I am not really good at Python and building/publishing binary wheels on pypi has been a horrible experience, I don't want to keep doing that and I also generally want to reduce the amount of time I spent working on open source.

**Comment by shlomif** [comment]
> > any comments?
> 
> Yes grin
> 
> If you think your code changes are useful then please go ahead and merge them. If you break primesieve-python I won't blame you, but I will not fix it either. Sadly I have to let go primesieve-python, I am not really good at Python and building/publishing binary wheels on pypi has been a horrible experience, I don't want to keep doing that and I also generally want to reduce the amount of time I spent working on open source.

Thanks! I'll try to see.

**Comment by shlomif** [comment]
Seems like the changes have already been integrated into the master branch. Closing then.

**Pull request closed without merging**
