### PR TITLE
Update to latest lib, clean up tests

### PR DESCRIPTION
**Pull request by brl0**
Hey @shlomif, Glad to see you're taking this project on!

I had some time in December, and tinkered on this for a bit, but didn't quite get to the point of opening a PR.  
I thought I would open this up just in case there were any changes you wanted to go ahead and merge.

Thanks for helping continue to make Kim's great work accessible from Python!

### CODE REVIEW

**Comment by shlomif** [comment]
On Thu, 05 Jan 2023 08:50:11 -0800
Brian Larsen ***@***.***> wrote:

> Hey @shlomif, Glad to see you&#39;re taking this project on!
> 
> I had some time in December, and tinkered on this for a bit, but didn&#39;t
> quite get to the point of opening a PR. I thought I would open this up just
> in case there were any changes you wanted to go ahead and merge.
> 
> Thanks for helping continue to make Kim&#39;s great work accessible from
> Python!
> 

Thanks, Brian! I'll try to take a look.

> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/shlomif/primesieve-python/pull/49
> 
> -- Commit Summary --
> 
>   * Update to latest lib, clean up tests
> 
> -- File Changes --
> 
>     M .travis.yml (14)
>     M README.md (2)
>     M lib/primesieve (2)
>     M primesieve/_primesieve.pyx (8)
>     M primesieve/cpp_primesieve.pxd (6)
>     M primesieve/numpy/_numpy.pyx (12)
>     M primesieve/numpy/cpp_numpy.pxd (2)
>     M tests/test_primesieve.py (146)
>     D tests/test_primesieve_numpy.py (19)
> 
> -- Patch Links --
> 
> https://github.com/shlomif/primesieve-python/pull/49.patch
> https://github.com/shlomif/primesieve-python/pull/49.diff
> 



-- 

Shlomi Fish       https://www.shlomifish.org/
Selina Mandrake - The Slayer (Buffy parody) - https://shlom.in/selina

SGlau: You want to publish… As a fellow artist, I want to publish too.
Dr. Feldman: “Publish or Perish” - they always told us that when I got my
Ph.D.
    — https://www.shlomifish.org/humour/Summerschool-at-the-NSA/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
@brl0 : 1. there are conflicts.

2. I get an error on fedora:

```
/home/shlomif/progs/riddles/project-euler/primesieve-python/setup.py:167: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from numpy.distutils.ccompiler import CCompiler_compile
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing primesieve.egg-info/PKG-INFO
writing dependency_links to primesieve.egg-info/dependency_links.txt
writing top-level names to primesieve.egg-info/top_level.txt
reading manifest file 'primesieve.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'lib'
adding license file 'LICENSE'
writing manifest file 'primesieve.egg-info/SOURCES.txt'
running build_ext
building 'primesieve._primesieve' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
INFO: C compiler: gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fuse-ld=mold -fPIC

INFO: compile options: '-Ilib/primesieve/include -I/usr/include/python3.11 -c'
extra options: '-std=c++11'
INFO: gcc: primesieve/_primesieve.cpp
primesieve/_primesieve.cpp: In function ‘PyObject* __pyx_f_10primesieve_11_primesieve_primes(uint64_t, int, __pyx_opt_args_10primesieve_11_primesieve_primes*)’:
primesieve/_primesieve.cpp:1986:19: warning: comparison of integer expressions of different signedness: ‘long int’ and ‘uint64_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 1986 |   if (((__pyx_t_1 > __pyx_t_2) != 0)) {
      |         ~~~~~~~~~~^~~~~~~~~~~
primesieve/_primesieve.cpp:2002:19: warning: comparison of integer expressions of different signedness: ‘long int’ and ‘uint64_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 2002 |   if (((__pyx_t_1 > __pyx_t_3) != 0)) {
      |         ~~~~~~~~~~^~~~~~~~~~~
primesieve/_primesieve.cpp: In function ‘PyObject* __pyx_f_10primesieve_11_primesieve_n_primes(uint64_t, int, __pyx_opt_args_10primesieve_11_primesieve_n_primes*)’:
primesieve/_primesieve.cpp:2298:19: warning: comparison of integer expressions of different signedness: ‘long int’ and ‘uint64_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 2298 |   if (((__pyx_t_1 > __pyx_t_2) != 0)) {
      |         ~~~~~~~~~~^~~~~~~~~~~
primesieve/_primesieve.cpp:2314:19: warning: comparison of integer expressions of different signedness: ‘long int’ and ‘uint64_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 2314 |   if (((__pyx_t_1 > __pyx_t_3) != 0)) {
      |         ~~~~~~~~~~^~~~~~~~~~~
primesieve/_primesieve.cpp: In function ‘void __pyx_f_10primesieve_11_primesieve_8Iterator_jump_to(__pyx_obj_10primesieve_11_primesieve_Iterator*, uint64_t, int, __pyx_opt_args_10primesieve_11_primesieve_8Iterator_jump_to*)’:
primesieve/_primesieve.cpp:5582:27: error: ‘struct primesieve::iterator’ has no member named ‘jump_to’
 5582 |   __pyx_v_self->_iterator.jump_to(__pyx_v_start, __pyx_v_stop_hint);
      |                           ^~~~~~~
error: Command "gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fuse-ld=mold -fPIC -Ilib/primesieve/include -I/usr/include/python3.11 -c primesieve/_primesieve.cpp -o build/temp.linux-x86_64-cpython-311/primesieve/_primesieve.o -std=c++11" failed with exit status 1

```

**Comment by shlomif** [comment]
@brl0 : ping!

**Comment by brl0** [comment]
@shlomif, sorry for the lack of response.  I will try take a look at this soon.

**Comment by shlomif** [comment]
On Wed, 25 Jan 2023 17:18:32 -0800
Brian Larsen ***@***.***> wrote:

> @shlomif, sorry for the lack of response.  I will try take a look at this
> soon.
> 

Ack.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://github.com/shlomif/Freenode-programming-channel-FAQ

Academic Politics are so vicious precisely because the stakes are so low.
    — https://quoteinvestigator.com/2013/08/18/acad-politics/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
@brl0 : ping!

**Comment by shlomif** [comment]
Closing for now to avoid clutter.

**Pull request closed without merging**
