### PR TITLE
Latest version of primesieve

### PR DESCRIPTION
**Pull request by brl0**
First of all, thanks for the great package.

I have made the changes necessary to utilize the latest version of the primesieve library.  Currently, this is not pinned to a version of primesieve, but probably should be.  It looks like a new version may be released soon, so I thought I would hold off on pinning for now.
Also, it should be noted this was based on the python38 branch.

Let me know if any changes are needed.
Thanks!

### CODE REVIEW

**Comment by kimwalisch** [comment]
Awesome, thank you!

The reason why primesieve-python has not been upgraded yet to use the latest libprimesieve version is that I distribute binary wheels for Windows. The latest libprimesieve version requires a compiler that supports C++11 or later. However the binary wheel for Python-2.7 on Windows must be built using an ancient C++ compiler (MSVC 2008 or 2010) that does not support C++11. 

So my initial plan for primesieve-python was to wait until Python-2.7 has been fully deprecated and then upgrade primesieve-python to the latest libprimesieve version.

Do you know if there are still many Python 2.7 Windows users out there (compared to Python-3.x Windows users). If there are virtually no Python 2.7 Windows users left then I am OK with dropping Python 2.7 Windows support and upgrading to the latest libprimesieve.

**Comment by brl0** [comment]
IMHO, I think users of Python 2 can pin to the most recent version of primesieve-python that works for them:
`pip install "primesieve<=1.4.4"`
I plan to do some quick testing of the performance of the new array option vs numpy, hopefully the performance difference would be sufficiently minimal you can drop the dependency and simplify the build process.
I think it might make sense to release all of these changes as a new major version (2.0.0) of primesieve-python since they include some minor breaking changes.

**Comment by kimwalisch** [comment]
> I think it might make sense to release all of these changes as a new major version (2.0.0) of primesieve-python since they include some minor breaking changes.

I agree, this is a good idea.

> I plan to do some quick testing of the performance of the new array option vs numpy, hopefully the performance difference would be sufficiently minimal you can drop the dependency and simplify the build process.

I am very interested in the results of your benchmark!

**Comment by brl0** [comment]
It seems that I have everything working except for Python 2.7 on Windows.  The problem seems to be a missing C99 header file in the version of MSVC (9.0) needed for Python 2.7.

**Comment by brl0** [comment]
Regarding performance testing, the numpy extension was up to 2x as fast as the array extension.  The speedup factor diminished for larger samples.  Unfortunately I lost my results when a large sample size destabilized my system, so I am unable to provide any more specifics.  I think the speed was close enough that dropping numpy support would not be catastrophic performance-wise, and I think it is really a judgement call based on the difficulty of continued support.  
Finally, part of the speed difference between the submodules and main module may be due to the difference between the C++ interface and C interface.  It may be worthwhile to transition the main module over to the C interface.
I hope this helps.  Let me know if there are any questions or concerns.

**Comment by kimwalisch** [comment]
Thanks for all your work!

I have a few questions & suggestions:

1) primesieve 6.0 and later don't use OpenMP anymore. So we can get rid of OpenMP detection in ```setup.py```. However on Unix-like OSes we might need to add ```-pthread``` to the linker flags because libprimesieve now uses C++11 multi-threading.

2) Can you please explain your commit: ```Skip parallel compile on 36,37. Change SDK for 27.```. Why is it not possible to use parallel compilation here?

> It seems that I have everything working except for Python 2.7 on Windows. The problem seems to be a missing C99 header file in the version of MSVC (9.0) needed for Python 2.7.

Older primesieve versions included a portable version of ```stdint.h``` for MSVC <= 2010. Here it is: https://github.com/kimwalisch/primesieve/blob/v5.7.1/src/msvc_compat/stdint.h. We could add a ```msvc_compat``` directory with that header and then add that directory to the include path in ```setup.py``` for MSVC <= 2010. The most difficult part would be to detect MSVC <= 2010 in ```setup.py```.

> Regarding performance testing, the numpy extension was up to 2x as fast as the array extension. The speedup factor diminished for larger samples.

Having a nice simple API and maintainability is more important to me then absolute best performance. Also I consider ```primesieve::iterator``` to be the most important feature and this feature would not suffer any performance degradation if we removed the ```primesieve.numpy``` module.

**Question:** Currently ```primesieve.primes(n)``` returns a python list of the primes <= n. Do you think it would be a good idea if  ```primesieve.primes(n)``` would return an array instead? This way we could further simplify primesieve-python, there would be only a single module which contains all functionality. Also currently ```primesieve.primes(n)``` is rather slow, by returning an array we could make it much faster...

**Comment by kimwalisch** [comment]
One issue I want to avoid is to have a lot of duplication. With the addition of the new ```primesieve.array``` module there would be 3 different ways to generate an array of primes:

* ```primesieve.primes(n)```
* ```primesieve.array.primes(n)```
* ```primesieve.numpy.primes(n)```

**Comment by brl0** [comment]
> 1. primesieve 6.0 and later don't use OpenMP anymore. So we can get rid of OpenMP detection in `setup.py`. However on Unix-like OSes we might need to add `-pthread` to the linker flags because libprimesieve now uses C++11 multi-threading.

I will take a look at this.

> 2. Can you please explain your commit: `Skip parallel compile on 36,37. Change SDK for 27.`. Why is it not possible to use parallel compilation here?

Great question.  Going back to your branch to update to Python 38, builds have been hanging on Python 36 and 37.  I did not have one successful build on those versions until, on an inexplicable hunch, I made this change.  Your changes to support Py38 were minor, so I am not sure whether the problem started there, or if the problem is related to distutils or something else.  I am able to parallel build on my machine with Py37 in both Windows and Linux (WSL Ubuntu 18.10).

> Older primesieve versions included a portable version of `stdint.h` for MSVC <= 2010. Here it is: https://github.com/kimwalisch/primesieve/blob/v5.7.1/src/msvc_compat/stdint.h. We could add a `msvc_compat` directory with that header and then add that directory to the include path in `setup.py` for MSVC <= 2010. The most difficult part would be to detect MSVC <= 2010 in `setup.py`.

Good to know.  Since this is an issue building primesieve, should this be added to that project?  If so, would you like me to create a pull request?

> Having a nice simple API and maintainability is more important to me then absolute best performance. Also I consider `primesieve::iterator` to be the most important feature and this feature would not suffer any performance degradation if we removed the `primesieve.numpy` module.

Understood.  One thought is you might want to make one last update release based roughly on where this PR stands since it does not include any breaking changes.  Of course, that is, after I correct the old msvc header issue, and any other fixes or changes you want.

> **Question:** Currently `primesieve.primes(n)` returns a python list of the primes <= n. Do you think it would be a good idea if `primesieve.primes(n)` would return an array instead? This way we could further simplify primesieve-python, there would be only a single module which contains all functionality. Also currently `primesieve.primes(n)` is rather slow, by returning an array we could make it much faster...

I agree and think this should be the path forward.  Since this is a breaking change, it should probably be considered a major release and have the version number reflect that.  

Along these lines, based on some quick testing, it seems the C interface is noticeably faster than the C++ interface.  To test, I created another submodule based on the array submodule, and modified it to include the C++ interface rather than C.  The performance matched very closely with the base module, with the array submodule based on the C interface performing much better.

So with all that said, my suggestion is to migrate the base module to the C interface, along with changing the return type to arrays rather than lists, and drop the numpy submodule for simplicity.  These changes could then be released as version 2.0.  I am happy to work on this if you would like.

**Comment by brl0** [comment]
Perhaps a little off-topic... 
What is your preference regarding ongoing support for Python 2?  It's EOL in 6 weeks or so, but there is still a trickle of download activity on [PyPI](https://pypistats.org/packages/primesieve).

Also, do you think we should add PyPy to the pipeline matrix?

**Comment by kimwalisch** [comment]
> What is your preference regarding ongoing support for Python 2? It's EOL in 6 weeks or so, but there is still a trickle of download activity on PyPI.

Let me handle this issue (```stdint.h```). If it is easy to fix we keep Python 2.7 support otherwise we will drop it.

> Understood. One thought is you might want to make one last update release based roughly on where this PR stands since it does not include any breaking changes. Of course, that is, after I correct the old msvc header issue, and any other fixes or changes you want.

Personally I would prefer to release this as version 2.0. This way I will have do to only 1 release.

> I agree and think this should be the path forward (use array for ```primesieve.primes```). Since this is a breaking change, it should probably be considered a major release and have the version number reflect that.

Great, this is a feature where I would appreciate your help because I am not a python expert. I can do everything but I am a bit slow.

> Along these lines, based on some quick testing, it seems the C interface is noticeably faster than the C++ interface. To test, I created another submodule based on the array submodule, and modified it to include the C++ interface rather than C. The performance matched very closely with the base module, with the array submodule based on the C interface performing much better.

If we can get better performance using the C API rather than the C++ API then I think it would be great to use the C API instead of the C++ API.

I suggest that I work on ```setup.py``` (e.g. get rid of OpenMP, add ```-pthread```) and also try to get rid of the ```primesieve.numpy``` module.

> Also, do you think we should add PyPy to the pipeline matrix?

Yes, that is a good idea.

**Comment by kimwalisch** [comment]
> Let me handle this issue (stdint.h). If it is easy to fix we keep Python 2.7 support otherwise we will drop it.

I just realised that we cannot support Python 2.7 on Windows since primesieve-7.5 requires C++11 but MSVC 2008 (or 2010) which is used to build the binary wheel for Python 2.7 does not support C++11. So we drop Python 2.7 support as it makes no sense to support Python 2.7 if we cannot support it on all operating systems.

We will simply update the README.md installation section to something like:

 ### Installation

```
pip install primesieve
````

For Python 2.7 use:

````
pip install "primesieve<=1.4.4"
````

**Comment by brl0** [comment]
As far as I can tell, the main thing left to do is to remove the numpy submodule and associated artifacts (setup, tests, travis, appveyor).  Let me know if I can be of assistance with that or anything else.

**Comment by brl0** [comment]
One other quick point... this branch is currently on the master branch of the primesieve repo.  It may be better to pin it to a specific branch or commit.

**Comment by kimwalisch** [comment]
I have found a solution for the parallel build that seems to work (all tests pass):

```python
# --------------------- Parallel build -------------------------------
# https://stackoverflow.com/a/55670555

try:
    from numpy.distutils.ccompiler import CCompiler_compile
    import distutils.ccompiler
    distutils.ccompiler.CCompiler.compile = CCompiler_compile
except ImportError:
    print("Numpy not found, parallel compile not available.")
```

**Comment by kimwalisch** [comment]
After I removed the ```primesieve.numpy``` module (on my v2.0 branch) I ran a few benchmarks using the code below:

```python
def test_primes_array():
    for x in range(10000000, 10002000):
        primes(x)
```

Timing for old ```primesieve.primes()```: 51.30s
Timing for new ```primesieve.primes()```: 16.81s
Timing for ```primesieve.numpy.primes()```: 5.28s

So the new ```primesieve.primes()``` implementation is about 3x faster which is great! However the numpy code is still 3x faster than the new ```primesieve.primes()``` implementation. For this reason I would like to keep ```primesieve.numpy``` module as I predict there will we users that care if their code runs 3x faster.

**Pull request merged**
